# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tfgg484-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir W:/vivado/DemoStudy/51_eth_udp_loop/eth_udp_loop/eth_udp_loop.cache/wt [current_project]
set_property parent.project_path W:/vivado/DemoStudy/51_eth_udp_loop/eth_udp_loop/eth_udp_loop.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/arp/arp.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/arp/arp_rx.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/arp/arp_tx.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/arp/crc32_d8.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/eth_ctrl.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/gmii_to_rgmii/gmii_to_rgmii.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/icmp/icmp.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/icmp/icmp_rx.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/icmp/icmp_tx.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/gmii_to_rgmii/rgmii_rx.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/gmii_to_rgmii/rgmii_tx.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/udp/udp.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/udp/udp_rx.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/udp/udp_tx.v
  W:/vivado/DemoStudy/51_eth_udp_loop/rtl/eth_udp_loop.v
}
read_ip -quiet W:/vivado/DemoStudy/51_eth_udp_loop/eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/async_fifo_2048x8b/async_fifo_2048x8b.xci

read_ip -quiet W:/vivado/DemoStudy/51_eth_udp_loop/eth_udp_loop/eth_udp_loop.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc W:/vivado/DemoStudy/51_eth_udp_loop/eth_udp_loop/eth_udp_loop.srcs/constrs_1/eth_udp_loop.xdc
set_property used_in_implementation false [get_files W:/vivado/DemoStudy/51_eth_udp_loop/eth_udp_loop/eth_udp_loop.srcs/constrs_1/eth_udp_loop.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top eth_udp_loop -part xc7a35tfgg484-2


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef eth_udp_loop.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file eth_udp_loop_utilization_synth.rpt -pb eth_udp_loop_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
